### ISSUE TITLE
❓ Question: http://localhost:3000/upload

### ISSUE THREAD

**Issue by antitiron** [stonith404/pingvin-share#220]
### 🙋‍♂️ Question

Hello!

Thank you for a great product.

However, a problem has now arisen. I have updated the contjner to a new version and suddenly when I go to the url it redirects to http://localhost:3000/upload.

Can you help?

```
version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    container_name: pingvin-share
    restart: unstopped
    ports:
      - 3000:3000
    volumes:
      - /data/docker/pingvin-share/data:/opt/app/backend/data
      - /data/docker/pingvin-share/data/images:/opt/app/frontend/public/img
```

**Comment by PastaGringo** [comment]
Hi,

I have the same issue.

With the docker image stonith404/pingvin-share:v0.17.1 it's working back for me !

PS : I'm using Nginx Proxy Manager to do the Reverse Proxy

**Comment by stonith404** [comment]
Sorry guys :/ I'm trying to fix it.

**Comment by stonith404** [comment]
I think it's only a caching issue. Could you guys try to open Pingvin Share in a private window and let me know if it works?

**Comment by PastaGringo** [comment]
Yes I saw some cache issue but even with private browsing I had the issue.
Another bug I found is that I can't create shares with unlimited duration.
Everything is OK with 17.0. I will try tomorrow to reinstall the v17.3.

**Comment by stonith404** [comment]
Hm okay. You don't have to reinstall Pingvin Share, it won't fix it. I made a potential fix on the image `pingvin-share:development`. Could you try to use this image and let me know if it works?

Btw. the issue with unlimited duration should be fixed in `v0.17.3`

**Comment by toniexly** [comment]
does it have something to do with disabling the homepage?? i disable the homepage and i got this same problem.

**Comment by toniexly** [comment]
> pingvin-share:development

I've tested this image. the issue persists.

**Comment by antitiron** [comment]
Hello!

> Could you guys try to open Pingvin Share in a private window and let me know if it works?
Checked, the error persists.

> I made a potential fix on the image pingvin-share:development. Could you try to use this image and let me know if it works?
Checked, the error persists.

I also confirm that:
1. The homepage disabled;
2. Using Nginx Proxy Manager to do the Reverse Proxy (http://pingvin-share:3000 to suddomain).

**Comment by toniexly** [comment]
reinstalling PingvinShare and clearing my browser's cache n cookies. without either of these, the homepage won't open.

i also confirm:
   if i do not touch "app url" and "show homepage", it works fine. though the logout action still redirects me to http://localhost:3000/auth/signIn?redirect=%2Fadmin

**Comment by stonith404** [comment]
Thanks you all for the help! Could you try the lastest development image again. I think I've found a solution.

**Comment by antitiron** [comment]
> Thanks you all for the help! Could you try the lastest development image again. I think I've found a solution.
Yeah, it's work!

**Comment by stonith404** [comment]
Awesome! `v0.17.4` with the fix should be pushed to Docker hub in an hour.

**Comment by antitiron** [comment]
Thanks for help! You're the best.

**Comment by PastaGringo** [comment]
Everthing is OK with the new v0.17.4 !
Thanks for your quick help @stonith404 !

**Comment by fame-odoo** [comment]
Hi, I just met this problem on the latest image, does anyone have this issue?
