### ISSUE TITLE
🐛 Bug Report: Several issues with OIDC

### ISSUE THREAD

**Issue by Toastyyy3** [stonith404/pingvin-share#780]
### 👟 Reproduction steps

Hey,

I recently discovered pingvin and wanted to check if it meets our requirements.

I first installed pingvin bare metal. As several things didn't work there, I verified all issues using the [Proxmox Helper Script](https://community-scripts.github.io/ProxmoxVE/scripts?id=pingvin) install.

So the environment is Debian 12, nodejs versions tried were 16 and 22, OIDC provider is Authentik.

Things I tried:
1. Configuring OIDC via config.yaml and the UI
2. Login with an authentik user that has the same username and email as a pingvin user
3. Assign admin privileges to an authentik user via oidc-roleAdminAccess
4. Assign admin privileges to an authentik user via pingvin UI

All those issues led me to thinking I misconfigured something but after looking at it and setting it up several days in a row, I can't figure out any mistakes in the configuration or setup.

### 👍 Expected behavior

1. I'd expect both configuration methods to work
2. I'd expect the authentik user to be connected to the existing pingvin user
3. I'd expect members of the specified groups to be assigned admin privileges
4. I'd expect the privileges inside pingvin to override the ones from authentik and to be persistent. Maybe one wants to choose a specific admin for pingvin without granting him access to all other Authentik managed services.

### 👎 Actual Behavior

1. Configuring the OIDC using the config.yaml does not work. The browser shows the following error:
{"statusCode":500,"message":"Internal server error"}. The logs show:
```
[Nest] 5601  - 03/01/2025, 1:46:20 PM   ERROR [ExceptionsHandler] Failed to parse URL from 
0|pingvin- | TypeError: Failed to parse URL from 
0|pingvin- |     at node:internal/deps/undici/undici:13502:13
0|pingvin- |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
0|pingvin- |     at async OidcProvider.fetchConfiguration (/opt/pingvin-share/backend/dist/src/oauth/provider/genericOidc.provider.js:141:21)
0|pingvin- |     at async OidcProvider.getConfiguration (/opt/pingvin-share/backend/dist/src/oauth/provider/genericOidc.provider.js:29:13)
0|pingvin- |     at async OidcProvider.getAuthEndpoint (/opt/pingvin-share/backend/dist/src/oauth/provider/genericOidc.provider.js:40:31)
0|pingvin- |     at async OAuthController.auth (/opt/pingvin-share/backend/dist/src/oauth/oauth.controller.js:44:21)
```
It works when configuring OIDC via the UI. The used configuration parameters were identical.
```oidc-enabled: "true"
  #Discovery URI of the OpenID Connect OAuth app
  oidc-discoveryUri: "https://authentik.domain.com/application/o/pingvin-share/.well-known/openid-configuration"
  #Whether the “Sign out” button will sign out from the OpenID Connect provider
  oidc-signOut: "false"
  #Scopes which should be requested from the OpenID Connect provider.
  oidc-scope: openid email profile
  #Username claim in OpenID Connect ID token. Leave it blank if you don't know what this config is.
  oidc-usernameClaim: "preferred_username"
  #Must be a valid JMES path referencing an array of roles. Managing access rights using OpenID Connect roles is only recommended if no other ide>
  oidc-rolePath: ""
  #Role required for general access. Must be present in a user’s roles for them to log in. Leave it blank if you don't know what this config is.
  oidc-roleGeneralAccess: ""
  #Role required for administrative access. Must be present in a user’s roles for them to access the admin panel. Leave it blank if you don't kno>
  oidc-roleAdminAccess: "Server Management"
  #Client ID of the OpenID Connect OAuth app
  oidc-clientId: "CLIENT_ID"
  #Client secret of the OpenID Connect OAuth app
  oidc-clientSecret: "CLIENT_SECRET"
```

2. I created an admin user with the same username and email as in Authentik. Once I login via authentik, the user is overwritten and thus the account with admin privileges gone.

3. I tried setting the oidc-roleAdminAccess to enable all Authentik admins to also have admin rights in pingvin. The name of the group in Authentik is "Server Management". When I set it, the users of the group do not have admin privileges. I first thought maybe it's due to the space but even with a group name without space it didn't work, also tried capitalization etc. The groups are handled within the profile scope in authentik afaik.

4. I logged in with an OIDC user, the account got created and then I tried giving that account admin privileges inside pingvin. Those privileges were revoked once the OIDC user logged in again.

**Comment by stonith404** [comment]
If you configure OIDC with the Yaml file do you see the discovery URI in the UI like this?

![Image](https://github.com/user-attachments/assets/9b9c793e-eae9-4934-9c73-7e4f9992df8b)

Is the following info box visible on the admin page?

![Image](https://github.com/user-attachments/assets/2257629c-4d27-42b2-b207-9c4af8ae8d17)

**Comment by Toastyyy3** [comment]
Sorry for the late reply, I missed the notification.

Yes, all values entered in the .yaml are shown in the config UI

**Comment by stief** [comment]
Just wanted to chip in here, I'm seeing the exact same behavior using MS Entra ID OAuth.
This started happening in v1.10.1 so for now, I've reverted back to v1.9.1 which is working just fine.
I am using the UI for configuration.

I'm running this in an Azure container app so logs are hard to grab. I've tried looking at the log stream but can't see anything.
The scenario is:

- User sign-in via MS Entra ID OAth
- Assign user Admin privileges
- As long as user is signed in, everything works fine
- User does a new sign-in, either via incognito tab or by sign-out -> sign-in
- Admin privileges are automagically removed

It's like the account gets overwritten, or perhaps recreated for some reason.

**Comment by stonith404** [comment]
How does the groups claim look like? Is it a string or array?

**Comment by Toastyyy3** [comment]
In authentik it's an array (see [source code](https://github.com/goauthentik/authentik/blob/2bdc41506817d3e4efb3386034b12ac88df0a753/blueprints/system/providers-oauth2.yaml#L45))

**Comment by stonith404** [comment]
Thanks, I'll look into it.

**Comment by Toastyyy3** [comment]
Thank you so much, very looking forward. The tool looks amazing so far, great work!

**Comment by sebastianfredette** [comment]
For what it's worth, I'm seeing identical behavior via Pocket-ID OIDC auth as well. 

Thanks for the hard work!

**Comment by thelouisvivier** [comment]
> Just wanted to chip in here, I'm seeing the exact same behavior using MS Entra ID OAuth.
> This started happening in v1.10.1 so for now, I've reverted back to v1.9.1 which is working just fine.
> I am using the UI for configuration.
> 
> I'm running this in an Azure container app so logs are hard to grab. I've tried looking at the log stream but can't see anything.
> The scenario is:
> 
> - User sign-in via MS Entra ID OAth
> - Assign user Admin privileges
> - As long as user is signed in, everything works fine
> - User does a new sign-in, either via incognito tab or by sign-out -> sign-in
> - Admin privileges are automagically removed
> 
> It's like the account gets overwritten, or perhaps recreated for some reason.

Hello, same IDP and same observation : starting 1.10.x, admin privileges are dropped upon login.

For now I am sticking to latest version and I give myself admin role via sqlite in db.

We never used the role mapping via OIDC, only set it via Pingvin (or CLI with SQLite), and that was working before...

**Comment by adi-alpex** [comment]
Also facing this issue with google SSO and Citadel via OIDC, I have lost admin privileges... I have tried giving myself admin privileges by editing the sqlite database, but it resets itself now... this has happened on the 1.10.3 and 1.10.2

**Comment by stonith404** [comment]
1159d972a8c32a0d6bf53d161c2fc09e6f8dfb28 has introduced a bug which overwrites the current role if the role isn't set by the OIDC provider. 

Would you mind to checkout the `stonith404/pingvin-share:development` image and let me know if this patch fixes the issue for you?

**Comment by sebastianfredette** [comment]
Works for me! Just had to flip myself manually to admin by editing pingvin-share.db. After doing so, subsequent logins via OIDC don't reset my user to non-admin.

For those looking for a one-liner to test:

`<sqlite> UPDATE User SET isAdmin = true WHERE email = '__your admin user's email here___';`

**Comment by Toastyyy3** [comment]
Yes, that did indeed solve the issue with overwriting, thanks! The other issues still persist.
Let me know if I can help you in some way (e.g. finding out how Authentik handles something or so). Unfortunately I don't have any TypeScript or JavaScript experience at all so I won't be of much help coding.

**Comment by stonith404** [comment]
Sorry for my late response, I currently have much going on.

Thanks for the feedback. The bug with the role that gets reset should be fixed in `v1.10.4`. 

I'll look into the other bugs later.

**Comment by fussel132** [comment]
Also: if a user got the "admin" role assigned once he keeps the admin privileges even if the role gets removed by the oidc provider

**Comment by TheDarkula** [comment]
I am running pingvin share `v1.11.1` and keycloak.

I tried configuring OIDC via `config.yaml` with this:
```
  oauth:
    oidc-discoveryUri: "https://auth.domain.com/realms/realmname/.well-known/openid-configuration"
```

This fails with:
```
[Nest] 78  - 04/21/2025, 8:26:20 AM   ERROR [ExceptionsHandler] Failed to parse URL from 
TypeError: Failed to parse URL from 
    at node:internal/deps/undici/undici:13502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OidcProvider.fetchConfiguration (/opt/app/backend/dist/src/oauth/provider/genericOidc.provider.js:138:21)
    at async OidcProvider.getConfiguration (/opt/app/backend/dist/src/oauth/provider/genericOidc.provider.js:29:13)
    at async OidcProvider.getAuthEndpoint (/opt/app/backend/dist/src/oauth/provider/genericOidc.provider.js:40:31)
    at async OAuthController.auth (/opt/app/backend/dist/src/oauth/oauth.controller.js:44:21)
```
I switched to trying OIDC via the UI. I tried specifying the "Path to roles in OpenID Connect token" with `pingvin-share-groups` in the UI, and the logs show this error:

```
[Nest] 72  - 04/21/2025, 8:14:49 AM    WARN [OidcProvider] Roles not found at path pingvin-share-groups in ID Token {
...
  "pingvin-share-groups": [
    "admins"
  ]
...
}
[Nest] 72  - 04/21/2025, 8:14:49 AM   ERROR [OidcProvider] User roles  do not include admins
[Nest] 72  - 04/21/2025, 8:14:49 AM   ERROR [ErrorPageExceptionFilter] {"error":"user_not_allowed"}
```

If I leave the "Path to roles in OpenID Connect token" setting blank, users can connect, but no admin privileges are assigned.

**Comment by stonith404** [comment]
All these issues should now be fixed in `v1.12.0`, or at least I can't reproduce them anymore. If you still encounter issues feel free to leave a comment.

**Comment by TheDarkula** [comment]
@stonith404 Unfortunately, this is still present with `1.12.0`.

I have tried with just the `admins` role, and also with the `users` role:

```
[Nest] 76  - 05/08/2025, 8:20:53 PM    WARN [OidcProvider] Roles not found at path pingvin-share-groups in ID Token {
...
  "pingvin-share-groups": [
    "admins"
  ],
...
}
[Nest] 76  - 05/08/2025, 8:20:53 PM   ERROR [OidcProvider] User roles  do not include users
[Nest] 76  - 05/08/2025, 8:20:53 PM   ERROR [ErrorPageExceptionFilter] {"error":"user_not_allowed"}
```

```
[Nest] 76  - 05/08/2025, 8:23:05 PM   ERROR [OidcProvider] User roles  do not include users
...
  "pingvin-share-groups": [
    "users",
    "admins"
  ],
...
}
```


This is the full oidc block from my config file:

```
  oauth:
    allowRegistration: "true"
    ignoreTotp: "true"
    disablePassword: "false"
    oidc-enabled: "true"
    oidc-discoveryUri: "https://auth.domain.com/realms/realmname/.well-known/openid-configuration"
    oidc-signOut: "true"
    oidc-scope: "openid email profile client-groups"
    oidc-usernameClaim: "preferred_username"
    oidc-rolePath: "pingvin-share-groups"
    oidc-roleGeneralAccess: "users"
    oidc-roleAdminAccess: "admins"
    oidc-clientId: "pingvin-share"
    oidc-clientSecret: "secret-here"
```
